### ISSUE TITLE
Completed tasks are persistent and won't go away

### ISSUE THREAD

**Issue by ryanaltvater** [rampatra/todobar-community#9]
![Screenshot 2024-11-04 at 5 05 50 PM](https://github.com/user-attachments/assets/73387aba-ae35-4bfb-9308-54b80c86acef)

**Steps to reproduce:**
1. Open the app
2. Add some tasks
3. Check a task's box to mark as "Complete"
4. Click out of the task list
5. Click back into the task list
6. "Complete" tasks still visible

**Comments:**
Once a task is marked as complete, it should be moved to a "Completed" list, or somewhere else that's not mixed in with tasks that haven't been completed yet. Over time, the list will get very tall as more items are added and the completed ones are still visible.

**Comment by ryanaltvater** [comment]
Agreed. I think both ways of working make sense.

I can absolutely see a task list showing completed tasks when you’re reporting to a team during a morning standup what you worked on that day.

For me, I use the app more just for myself and smaller tasks that don’t get reported up to the team for my standup updates. So I’m more less completing tasks to reduce that list, as visual progress of what’s left without the distraction of completed tasks mixed in.

**Comment by rampatra** [comment]
This issue has been addressed in version 2.0.0 (released a few days ago). Can you pl kindly update the app and check this? If you're happy, please close this after.

**Comment by ryanaltvater** [comment]
This did not work for me. I have the setting enabled, I've completed a test task, and I've clicked out of the app. It isn't until I fully quit the app and reopen it that the task disappears.

**Comment by rampatra** [comment]
https://github.com/user-attachments/assets/377470cf-8f93-49f5-a04a-1dce1b9b52f4

This again works as expected for me. I think you have some conflicting version with TestFlight or something.

**Comment by ryanaltvater** [comment]
I never got around to installing the TestFlight version before you released 2.0. So I only have the one version of the app, of which I've exited out of multiple times and I'm still experiencing the issue.

![Screenshot 2024-11-14 at 6 07 54 PM](https://github.com/user-attachments/assets/b81eb740-3ad1-4c22-ab84-02205f333488)

**Comment by ryanaltvater** [comment]
I have just completely uninstalled the app and reinstalled it. I'm still seeing all of the issue.
